packages:
  - "packages/*"
  - "apps/*"
  - "indexer/*"
allowBuilds:
  '@reown/appkit': false
enableGlobalVirtualStore: false
minimumReleaseAgeExclude:
  - '@wagmi/connectors@8.0.22'
  - '@wagmi/core@3.6.1'
  - wagmi@3.7.1
