// Generated by scripts/generate-doc-index.mjs. Do not edit by hand.
import type { DocHeading } from "./types";

export const generatedDocsIndex = {
  "contracts/architecture": {
    "headings": [
      {
        "depth": 2,
        "id": "contract-roles",
        "title": "Contract roles"
      }
    ],
    "searchText": "Feather uses Liquidity Book v2.2 contracts on Robinhood Chain. Verified mainnet integration details will publish after deployment validation. Contract roles - LBFactory registers pairs, presets, quote assets, and supported implementations. - LBPair holds reserves, executes bin-level swaps, and mints or burns liquidity balances. - LBToken defines fungible multi-token balances keyed by bin ID. - LBRouter prepares user-facing swap and liquidity operations across supported pairs. - LBQuoter computes candidate exact-input paths without executing them. Addresses, verified source links, method examples, and event examples remain withheld until the mainnet deployment passes release validation."
  },
  "contracts/events-errors": {
    "headings": [
      {
        "depth": 2,
        "id": "event-families",
        "title": "Event families"
      },
      {
        "depth": 2,
        "id": "error-handling",
        "title": "Error handling"
      }
    ],
    "searchText": "Verified event signatures and decoded examples will publish with mainnet contracts. Event families - Pair creation identifies tokens, bin step, and the new pair. - Swap records sender, recipient, active ID movement, amounts, fees, and protocol share. - Deposited-to-bins and withdrawn-from-bins identify affected IDs and packed token amounts. - Composition-fee events identify active-bin fees paid during imbalanced placement. - Transfer events move fungible bin balances between owners. Error handling Classify failures before retrying: invalid path, unsupported preset, stale active state, expired deadline, insufficient output, insufficient allowance, insufficient balance, unauthorized operator, or contract identity mismatch. Interpret logs against the exact verified contract address and block. Do not decode a matching topic from an unrelated contract as a Feather event."
  },
  "contracts/factory": {
    "headings": [
      {
        "depth": 2,
        "id": "integration-responsibilities",
        "title": "Integration responsibilities"
      }
    ],
    "searchText": "LBFactory is the authority for registered pairs, supported implementations, quote assets, and open bin-step presets. Integration responsibilities Before using a pair, resolve it from the verified factory and validate token order, bin step, implementation, and hook configuration. Before creating a pair, confirm both token contracts, quote-asset eligibility, open preset state, semantic price orientation, and duplicate-pair result. Read the registered pair identity for a token pair and bin step, then attest the returned contract before use. Create only after validating semantic token order, supported preset, initial active ID, and absence of an existing pair. Exact signatures and examples publish with the verified mainnet release."
  },
  "contracts/integration-recipes": {
    "headings": [
      {
        "depth": 2,
        "id": "pool-attestation",
        "title": "Pool attestation"
      },
      {
        "depth": 2,
        "id": "exact-input-swap",
        "title": "Exact-input swap"
      },
      {
        "depth": 2,
        "id": "add-liquidity",
        "title": "Add liquidity"
      },
      {
        "depth": 2,
        "id": "remove-liquidity",
        "title": "Remove liquidity"
      }
    ],
    "searchText": "Executable recipes will publish after verified mainnet addresses and source links are available. Pool attestation Resolve the pair from LBFactory, then compare factory, token order, bin step, hook configuration, and deployed code before reading executable state. Exact-input swap Quote a supported path, validate every leg, calculate minimum output, bind a deadline, confirm allowance, encode router calldata, and simulate from the final sender. Add liquidity Read the current active bin, construct no more than 69 bin weights, normalize each token side, set protected minima and refund destination, approve only nonzero token sides, and simulate exact value. Remove liquidity Enumerate the complete intended live balances, refresh reserves and supply at one current state, calculate protected outputs, verify operator approval, and simulate the exact burn set. Do not substitute test or placeholder contracts into a mainnet transaction."
  },
  "contracts/mainnet-deployments": {
    "headings": [
      {
        "depth": 2,
        "id": "verification-policy",
        "title": "Verification policy"
      }
    ],
    "searchText": "Mainnet addresses will appear only after the release process verifies chain ID, deployed code, constructor configuration, ownership state, and explorer source verification. Verification policy This page never publishes testnet, local development, dry-run, zero, or placeholder addresses as mainnet contracts. Integrators should compare addresses against the official explorer and the currently selected release before signing or encoding transactions. Wait for verified mainnet values. A syntactically valid address can still target the wrong chain or contract."
  },
  "contracts/pair-token": {
    "headings": [
      {
        "depth": 2,
        "id": "required-identity-checks",
        "title": "Required identity checks"
      },
      {
        "depth": 2,
        "id": "position-semantics",
        "title": "Position semantics"
      }
    ],
    "searchText": "LBPair holds market reserves and maps liquidity to bin IDs. LBToken behavior exposes each owner's fungible balance in those bins. Required identity checks Validate the factory, token X, token Y, bin step, hook configuration, deployed code, and active ID before preparing a write. Treat a deep link or visually matching symbol as untrusted until these checks agree. Position semantics An owner can hold balances across many bin IDs. Overlapping deposits merge. Removing liquidity burns selected balances and returns proportional current reserves. There is no unique position NFT and no independent LP fee claim. Read the owner's live balance for an exact bin ID and pair contract. Read current token reserves for one bin and combine them with total supply for proportional claims."
  },
  "contracts/quoter": {
    "headings": [
      {
        "depth": 2,
        "id": "safe-quote-handling",
        "title": "Safe quote handling"
      }
    ],
    "searchText": "LBQuoter evaluates registered candidate paths and returns expected amounts and fee information without changing state. Safe quote handling Validate every returned pair, token transition, bin step, version, amount, and fee. Reject routes that are empty, inconsistent, use an unsupported version, or differ from the original request. A quote becomes stale when pool state, amount, direction, token metadata, chain, or deployment changes. Build the router path from the exact reviewed quote and simulate it again before submission. Apply an explicit minimum received and deadline. A read-only quote cannot guarantee later execution or reserve availability. Exact verified signatures and examples publish with the mainnet deployment."
  },
  "contracts/router": {
    "headings": [
      {
        "depth": 2,
        "id": "transaction-requirements",
        "title": "Transaction requirements"
      }
    ],
    "searchText": "LBRouter coordinates user-facing swaps, liquidity additions, and liquidity removals. Transaction requirements Bind the exact account, chain, router, pool path, token order, amounts, slippage protection, deadline, recipient, refund destination, and native value. Simulate the final calldata from the sending account immediately before wallet handoff. Use a verified v2.2 path and protect minimum output. Refresh quote and allowance after any bound context changes. Supply validated bin IDs and independently normalized token distributions with protected minimum amounts. Burn exact live balances with protected token outputs and current pair-wide operator approval. Exact signatures and examples publish after mainnet verification."
  },
  "contracts/safety-checklist": {
    "headings": [
      {
        "depth": 2,
        "id": "before-encoding",
        "title": "Before encoding"
      },
      {
        "depth": 2,
        "id": "before-submission",
        "title": "Before submission"
      },
      {
        "depth": 2,
        "id": "after-submission",
        "title": "After submission"
      }
    ],
    "searchText": "Before encoding - Confirm Robinhood Chain mainnet and the current verified deployment. - Attest factory, pair code, token order, bin step, and hooks. - Reject unsupported tokens, presets, versions, and paths. - Distinguish native ETH from WETH. Before submission - Bind sender, recipient, refund destination, target, calldata, and native value. - Use explicit minimum outputs and bounded deadlines. - Disclose exact ERC-20 allowances and pair-wide operator approvals. - Refresh balance, allowance, active state, and quote after every prerequisite. - Simulate the exact transaction from the final sender. After submission - Track the hash, replacements, receipt status, and required confirmations. - Reconcile token balances, native balance, live bin balances, and expected events. - Treat unknown submission, reorganization, revert, and delayed views as distinct states. If identity, completeness, freshness, or simulation cannot be established, do not construct or submit the write."
  },
  "getting-started/before-you-begin": {
    "headings": [
      {
        "depth": 2,
        "id": "use-small-amounts-first",
        "title": "Use small amounts first"
      }
    ],
    "searchText": "Before using Feather, make sure you control the selected wallet and understand the assets you intend to trade or supply. 1. Install and unlock a supported wallet. 2. Select the intended account and Robinhood Chain. 3. Keep ETH available for network fees. 4. Verify token addresses, not symbols alone. 5. Read the pool address, bin step, current price, and fee information. 6. Review every approval and transaction in the wallet before signing. Use small amounts first If a token, pool, strategy, or wallet workflow is new to you, begin with an amount you can afford to lose. Confirm the resulting balances and activity before increasing exposure. Do not enter a seed phrase or private key into the application, documentation, support messages, or vulnerability reports."
  },
  "getting-started/connect": {
    "headings": [
      {
        "depth": 2,
        "id": "connect",
        "title": "Connect"
      },
      {
        "depth": 2,
        "id": "switch-networks",
        "title": "Switch networks"
      },
      {
        "depth": 2,
        "id": "disconnect-or-change-accounts",
        "title": "Disconnect or change accounts"
      }
    ],
    "searchText": "Connect Choose Connect , select the intended wallet if more than one is available, and approve account access in the wallet. Feather displays the connected address after the provider confirms access. Common connection failures include a locked wallet, rejected permission, no installed provider, or a provider that has not authorized the site. Unlock the wallet or grant access, then retry from the application. Switch networks When prompted, inspect the requested chain details in the wallet. Reject an unexpected chain. After a successful switch, Feather reloads chain-specific pools, balances, approvals, and positions. Disconnect or change accounts Disconnecting clears the local connection. Changing accounts invalidates any unsubmitted review because owner, balance, allowance, and recipient context changed. After the wallet receives or broadcasts a transaction, later form edits create a separate draft. They do not alter the original request or hash."
  },
  "getting-started/first-pool": {
    "headings": [
      {
        "depth": 2,
        "id": "identity",
        "title": "Identity"
      },
      {
        "depth": 2,
        "id": "market-state",
        "title": "Market state"
      },
      {
        "depth": 2,
        "id": "choose-an-action",
        "title": "Choose an action"
      }
    ],
    "searchText": "Open a pool from Discover and verify its exact identity before trading or providing liquidity. Identity Confirm the token names and addresses, pool contract address, token order, and bin step. Feather uses the chain selected by the deployed application; verify the requested chain in your wallet before signing. Two pools can use the same tokens while having different addresses and economic behavior. Market state Review the displayed price, liquidity distribution, fee parameters, and recent price activity. Missing USD values are not the same as zero value. Empty pools have no executable swap liquidity. Choose an action - Swap exchanges one pool asset for the other. - Create Position distributes supplied assets across selected bins. - Manage inspects or removes liquidity already owned by the connected wallet. Action panels retain the selected pool. If the address or bin step changes, Feather requires a new review rather than silently substituting another pool."
  },
  "getting-started/tokens": {
    "headings": [
      {
        "depth": 2,
        "id": "supported-assets",
        "title": "Supported assets"
      },
      {
        "depth": 2,
        "id": "balance-precision",
        "title": "Balance precision"
      }
    ],
    "searchText": "A token symbol is not unique. Confirm the network and full contract address whenever you select, approve, or receive an asset. Supported assets Feather only enables actions for assets that meet its configured support policy. Unsupported addresses may be identifiable, but they cannot be silently imported into an executable transaction. Assets with known transfer taxes, rebasing behavior, unsupported approval behavior, or other incompatible controls can be restricted or blocked. Balance precision Token decimals determine how the displayed amount maps to the integer value transferred onchain. Inputs with too many decimals, scientific notation, negative values, or amounts above the available balance are rejected. Selecting Max for ETH preserves a gas reserve. Selecting Max for an ERC-20 token does not change the separate ETH requirement. A verified address confirms identity, not quality, safety, market value, or future behavior."
  },
  "getting-started/wallet-network": {
    "headings": [
      {
        "depth": 2,
        "id": "network-identity",
        "title": "Network identity"
      },
      {
        "depth": 2,
        "id": "account-identity",
        "title": "Account identity"
      }
    ],
    "searchText": "Feather supports the wallet choices presented by the application. On desktop, this may include MetaMask or Brave Wallet when their browser providers are available and authorized. Network identity Robinhood Chain uses ETH as its native gas currency. The application checks both the wallet network and its own configured network before enabling a transaction. If the two network identities disagree, Feather blocks execution. Switching the visible wallet chain alone is not enough when the configured runtime reports another chain. Account identity The connected address determines balances, approvals, positions, and transaction context. Changing accounts clears or reloads owner-specific state. A pending transaction remains associated with the account and chain that submitted it. You can browse documentation and public pool information without connecting. Connect only when an action needs your account or signature."
  },
  "liquidity/composition-fees": {
    "headings": [
      {
        "depth": 2,
        "id": "before-signing",
        "title": "Before signing"
      },
      {
        "depth": 2,
        "id": "native-asset-refunds",
        "title": "Native-asset refunds"
      }
    ],
    "searchText": "An imbalanced deposit that touches the active bin can pay a composition fee. This is separate from gas and swap fees. Before signing The review should identify the estimated composition fee, any protocol share, protected net placement, and each expected refund asset. Volatility or active-bin changes invalidate the estimate and require refresh. Native-asset refunds When native ETH is supplied to a wrapped-native pool, unused native-side value can cross the contract boundary as WETH. The receipt view must reconcile both ETH and WETH balances rather than claiming every unused amount returned as ETH. The confirmed transaction events and balance changes determine actual fees and refunds. A preflight value is an estimate based on the reviewed state."
  },
  "liquidity/create-add": {
    "headings": [],
    "searchText": "1. Open the exact pool and choose Create Position or Add More . 2. Enter token amounts and choose a range of no more than 69 bins. 3. Select Spot, Curve, or Bid-Ask and inspect every projected weight. 4. Review minimum amounts, slippage, bin tolerance, deadline, recipient, refund destination, and gas estimate. 5. Complete each required approval. 6. Review refreshed balances and pool state, then submit the liquidity transaction. Adding to bins you already own increases the same fungible balances. The application may preserve deposit history for accounting, but it must not imply that overlapping deposits remain separately withdrawable. Each nonzero ERC-20 side can need its own approval before the final add. Approval success is not position creation."
  },
  "liquidity/fees-pnl": {
    "headings": [
      {
        "depth": 2,
        "id": "current-claims",
        "title": "Current claims"
      },
      {
        "depth": 2,
        "id": "cost-basis-and-profit-or-loss",
        "title": "Cost basis and profit or loss"
      }
    ],
    "searchText": "Current claims Current value begins with the position's proportional token claims in each live bin. Trading and eligible composition fees retained by bins increase those reserves over time. Cost basis and profit or loss Feather uses proportional average basis per bin when complete event history and trusted prices are available. Deposits add basis, partial withdrawals release basis in proportion to liquidity burned, and direct balance transfers move the known proportional basis. Missing prices, incomplete history, or unexplained transfers make affected USD values or P&L partial or unavailable. They are not replaced with zero. Displayed basis and P&L are not tax advice and may not match the rules that apply to you. Preserve your own transaction records and consult a qualified professional. There is no independent fee-claim balance. Removing liquidity realizes underlying reserves and embedded fee value together."
  },
  "liquidity/manage": {
    "headings": [
      {
        "depth": 2,
        "id": "position-status",
        "title": "Position status"
      },
      {
        "depth": 2,
        "id": "available-actions",
        "title": "Available actions"
      }
    ],
    "searchText": "Portfolio groups every live balance owned by the connected wallet in each pool. Open a position to inspect individual bins and current claims. Position status - In range: the wallet owns a nonzero balance in the active bin. - Out of range: live balances remain, but none are in the active bin. - Empty: no positive live bin balance remains. - Partial: the complete owned-bin set or accounting history is not currently available. Current token claims include the position's share of reserves and embedded fee value. There is no separate Claim Fees transaction. Available actions Add More returns to the same pool with current context. Withdraw selects a percentage and bins. Full Exit targets every live positive bin owned in that pool. A shared position URL can display another address, but write actions remain disabled unless the connected wallet owns the live balances."
  },
  "liquidity/multi-transaction-exits": {
    "headings": [
      {
        "depth": 2,
        "id": "batch-behavior",
        "title": "Batch behavior"
      }
    ],
    "searchText": "A position with many live bins can exceed a safe single-transaction limit. Feather splits it into simulated batches only when the complete position is known. Batch behavior Each batch has its own bin set, review, gas estimate, wallet request, hash, and receipt. Before the next batch, Feather refreshes the remaining live balances and rebuilds the plan. If one batch is rejected or reverts, already confirmed batches remain final. Resume from the remaining set rather than replaying completed burns. Price, reserves, and composition can change between transactions. The position is not fully exited until every positive live balance is zero. When safe batching is unavailable, Feather blocks the action instead of constructing a transaction expected to exceed limits."
  },
  "liquidity/one-sided": {
    "headings": [
      {
        "depth": 2,
        "id": "eligible-ranges",
        "title": "Eligible ranges"
      },
      {
        "depth": 2,
        "id": "review-carefully",
        "title": "Review carefully"
      }
    ],
    "searchText": "One-sided liquidity deposits only token X or only token Y. Feather does not silently swap one asset into the other. Eligible ranges A range wholly above the active bin can receive token X. A range wholly below the active bin can receive token Y. The interface blocks an incompatible asset and explains which side the range accepts. Review carefully Inspect the active bin, selected range, nonzero asset amount, zero asset amount, projected weights, approval requirement, and refund behavior. If the market moves across the selected range before execution, the earlier review becomes stale. If you need the other pool asset, acquire it through a separately reviewed trade. A direct one-sided add is not a swap or Zap."
  },
  "liquidity/out-of-range": {
    "headings": [
      {
        "depth": 2,
        "id": "available-choices",
        "title": "Available choices"
      }
    ],
    "searchText": "A position is out of range when it has live balances but none in the active bin. It may stop participating in current swaps and can become heavily or fully composed of one token. Available choices - Leave the position in place and accept inactive exposure. - Add liquidity to a new range while retaining the old balances. - Withdraw selected bins. - Exit and create a different position. Rebalancing normally means remove, wait for confirmation, then add through a new review. Market exposure exists between those transactions, and the final range can differ from the original intent if price moves. A successful removal does not guarantee the later add will be approved, simulated, affordable, or confirmed. Keep each step recoverable on its own."
  },
  "liquidity/primer": {
    "headings": [
      {
        "depth": 2,
        "id": "ownership-model",
        "title": "Ownership model"
      },
      {
        "depth": 2,
        "id": "fee-model",
        "title": "Fee model"
      }
    ],
    "searchText": "Liquidity providers deposit one or both pool assets across selected price bins. In return, the pair contract records fungible balances for each owned bin. Ownership model Your position is the complete set of nonzero bin balances held by one wallet in one pool. Overlapping deposits merge into those balances. A strategy name describes how a deposit was distributed, not a permanent onchain position type. Fee model Eligible trading and composition fees remain in bin reserves. They increase the token claims represented by outstanding liquidity. Withdrawing burns liquidity and returns the corresponding reserves, including embedded fee value. Price movement, concentration, out-of-range time, token behavior, fees, gas, and contract risk can cause loss. Compare the result with simply holding both assets."
  },
  "liquidity/ranges-bins": {
    "headings": [
      {
        "depth": 2,
        "id": "position-relative-to-the-market",
        "title": "Position relative to the market"
      }
    ],
    "searchText": "A liquidity range is a contiguous selection of price bins. Narrow ranges concentrate capital near selected prices. Wide ranges spread it across more prices. Position relative to the market - Bins above the active bin accept token X. - Bins below the active bin accept token Y. - The active bin can accept both assets. - A range wholly on one side can support a direct one-sided deposit. Range handles, price fields, bin IDs, and displayed composition must stay synchronized. Feather supports at most 69 bins in one prepared range and rejects larger selections. A changed active bin can alter eligible composition, fees, or transaction parameters. Feather refreshes and requires a new review instead of submitting stale arrays."
  },
  "liquidity/strategies": {
    "headings": [],
    "searchText": "Strategies calculate relative weights across the selected bins. They do not create durable strategy accounts and do not rebalance automatically. Strategy Distribution Typical tradeoff --- --- --- Spot Equal weight across eligible bins Simple, even coverage Curve More weight toward the active price Greater near-market concentration Bid-Ask More weight toward range edges More edge concentration and different conversion behavior Each token side is normalized independently. The preview must match the exact bin IDs and weights sent for review. No distribution guarantees fee income, time in range, protection from conversion, or better performance than holding the tokens."
  },
  "liquidity/withdraw-exit": {
    "headings": [
      {
        "depth": 2,
        "id": "partial-withdrawal",
        "title": "Partial withdrawal"
      },
      {
        "depth": 2,
        "id": "full-exit",
        "title": "Full exit"
      }
    ],
    "searchText": "Partial withdrawal Choose selected bins and an exact percentage. The review calculates a burn amount per live balance and protects minimum token X and token Y outputs. A successful partial withdrawal leaves remaining balances in the position. Full exit Full Exit means 100% of every live positive bin balance owned by the connected wallet in the selected pool. A subset or percentage below 100% is never labeled a full exit. 1. Refresh the complete owned-bin set. 2. Reconcile live balances and pool reserves at one current state. 3. Review operator approval scope when required. 4. Inspect expected and minimum outputs, gas, and output asset policy. 5. Simulate and submit the exact burn transaction. 6. Confirm received assets and remaining bin balances. A position may return mostly or entirely one asset after market movement. A protected zero on one side can be valid when the other side remains protected."
  },
  "overview/glossary": {
    "headings": [
      {
        "depth": 2,
        "id": "market-terms",
        "title": "Market terms"
      },
      {
        "depth": 2,
        "id": "position-terms",
        "title": "Position terms"
      },
      {
        "depth": 2,
        "id": "transaction-terms",
        "title": "Transaction terms"
      }
    ],
    "searchText": "Market terms A discrete price point that can hold token reserves and liquidity balances. The configured price interval between neighboring bins in a pool. The bin at the current pool price. The change in execution price caused by a swap consuming available liquidity. The user-selected difference allowed between the reviewed quote and protected execution boundary. Position terms One wallet's complete set of nonzero bin balances in one pool. The position owns liquidity in the active bin. The position has liquidity, but none in the active bin. A 100% burn of every live positive balance owned by the wallet in the selected pool. Transaction terms Permission granted to a contract to spend a token or operate Liquidity Book balances. A preflight execution against current chain state that checks whether the exact transaction is expected to succeed. A new block added after the block containing a transaction receipt."
  },
  "overview/liquidity-book": {
    "headings": [
      {
        "depth": 2,
        "id": "pools-and-bin-steps",
        "title": "Pools and bin steps"
      },
      {
        "depth": 2,
        "id": "fees-and-movement",
        "title": "Fees and movement"
      }
    ],
    "searchText": "Liquidity Book divides a market into discrete price bins. Each bin represents a price and holds reserves supplied by liquidity providers. Pools and bin steps A pool is identified by token X, token Y, and a bin step. The bin step controls the price distance between neighboring bins. The same token pair can have several pools with different bin steps, fees, and liquidity. The bin containing the pool's current trading price. Swaps can move the active bin as liquidity is consumed. All nonzero Liquidity Book balances owned by one wallet in one pool. It is not an NFT or a separate account. Fees and movement Trading fees stay inside pool reserves and increase the claims represented by liquidity balances. There is no separate fee-claim action. Fees are realized together with the underlying assets when liquidity is removed. Dynamic fees can rise during volatile activity. A higher displayed fee can improve fee collection for active liquidity, but it also changes trading cost and does not guarantee profit."
  },
  "overview/risks": {
    "headings": [
      {
        "depth": 2,
        "id": "market-and-liquidity-risk",
        "title": "Market and liquidity risk"
      },
      {
        "depth": 2,
        "id": "contract-and-token-risk",
        "title": "Contract and token risk"
      },
      {
        "depth": 2,
        "id": "approval-risk",
        "title": "Approval risk"
      }
    ],
    "searchText": "Every Feather action is an onchain transaction controlled by your wallet. Review the complete transaction request and understand the risks before signing. Market and liquidity risk Prices can move between review and confirmation. Swaps may receive less than the expected amount, subject to the selected minimum. Liquidity positions can become one-sided, move out of range, or lose value relative to holding the tokens separately. Contract and token risk Contracts can contain defects. Tokens can have unusual transfer behavior, mutable controls, blacklists, or misleading symbols. Feather restricts unsupported assets, but an allowlisted asset is not a promise of safety or value. Approval risk An ERC-20 allowance lets a spender transfer an approved token amount. A Liquidity Book operator approval can cover every bin balance issued by one pair contract. Verify both addresses and scopes. Reject any request with an unexpected account, chain, token, spender, recipient, value, or calldata target. A legitimate interface will let you stop and review again."
  },
  "overview/why-feather": {
    "headings": [
      {
        "depth": 2,
        "id": "for-traders",
        "title": "For traders"
      },
      {
        "depth": 2,
        "id": "for-liquidity-providers",
        "title": "For liquidity providers"
      }
    ],
    "searchText": "Feather is designed around exact pool context. The pool address, token order, bin step, current price, fees, liquidity, and transaction settings remain visible while you trade or manage liquidity. For traders - Choose the exact pool used for execution. - Review expected output, minimum received, fees, price impact, deadline, and current quote freshness. - Simulate the exact transaction before it reaches the wallet. For liquidity providers - Place capital into a narrow or wide range of price bins. - Choose Spot, Curve, or Bid-Ask distributions. - Provide one asset when the selected range supports direct one-sided liquidity. - Withdraw selected bins or exit the complete pool position. More precise controls let you express a strategy. They do not remove impermanent loss, out-of-range risk, token risk, gas cost, or smart-contract risk."
  },
  "pools/charts": {
    "headings": [
      {
        "depth": 2,
        "id": "price-chart",
        "title": "Price chart"
      },
      {
        "depth": 2,
        "id": "liquidity-distribution",
        "title": "Liquidity distribution"
      }
    ],
    "searchText": "Pool charts describe historical trading and current liquidity. They are decision aids, not execution guarantees. Price chart Price candles use a consistent base and quote orientation. Check the axis label before comparing the chart with another market. Volume must state whether it represents base-token, quote-token, or verified USD value. Gaps can mean no eligible activity or incomplete information. They must not be silently drawn as zero-volume trading. Liquidity distribution The distribution view places reserves across bounded bin IDs and marks the active bin. Each bin can contain token X, token Y, or both. A connected owner's overlay shows where owned balances sit relative to the market. Keyboard and screen-reader users receive the same values through a table or list representation. Always rely on the current action review, protected minimum, and wallet request for execution details."
  },
  "pools/create": {
    "headings": [],
    "searchText": "Pool creation follows Tokens, Configure, Review, and Create. 1. Choose distinct supported base and quote assets. 2. Select an available open bin-step preset. 3. Enter the initial quote-per-base price and inspect its inverse. 4. Review token order, addresses, bin step, initial active bin, fee parameters, factory, and gas estimate. 5. Submit the creation transaction. 6. Open the resulting pool and prepare initial liquidity separately when needed. The selected base and quote meaning controls displayed price. Address sorting used for duplicate detection must not silently reverse that meaning. An inaccurate initial price can be arbitraged. Confirm the price orientation, decimals, inverse value, and rounded representable result before signing. If another wallet creates the same pair and bin step first, Feather opens the winning pool and requires a fresh review against its live state."
  },
  "pools/discover": {
    "headings": [
      {
        "depth": 2,
        "id": "search-and-compare",
        "title": "Search and compare"
      },
      {
        "depth": 2,
        "id": "read-states-correctly",
        "title": "Read states correctly"
      }
    ],
    "searchText": "Discover lists available Liquidity Book pools and keeps each pool's address and bin step visible. Search and compare Search by token name, symbol, token address, or exact pool address. Same-symbol assets remain distinguishable by their addresses. When several pools use the same token pair, compare bin step, fees, liquidity, current price, and recent activity before opening one. Sort and filter controls change the visible list, not pool identity. Returning from a pool restores the prior discovery context when possible. Read states correctly - No results: the current search or filter matched no pool. - Empty: no pools are available for the selected environment. - Unavailable: current pool information could not be loaded. - Partial: some results are visible, but the list may be incomplete. Open the exact pool and verify its contract address before signing an approval or transaction."
  },
  "pools/duplicate-pools": {
    "headings": [
      {
        "depth": 2,
        "id": "compare-exact-pools",
        "title": "Compare exact pools"
      }
    ],
    "searchText": "One normalized token pair can have several Liquidity Book pools. Each bin step produces a distinct pool address and can produce different fees, liquidity concentration, price behavior, and execution quality. Compare exact pools Check: - full pool contract address; - semantic token order and price orientation; - bin step and current fee parameters; - active price and available reserves; - recent activity and current transaction quote. An optimized future route may intentionally leave the selected pool only when the review identifies every leg. Standard pool-context execution must never silently substitute another pool. Before creation or execution, Feather verifies the exact pair identity. A visually similar row or stale listing is not sufficient proof."
  },
  "pools/empty-pools": {
    "headings": [
      {
        "depth": 2,
        "id": "what-is-unavailable",
        "title": "What is unavailable"
      },
      {
        "depth": 2,
        "id": "add-initial-liquidity",
        "title": "Add initial liquidity"
      }
    ],
    "searchText": "A confirmed pool can exist before it has liquidity. The workspace displays its initial price and creation state without inventing volume, value, or reserves. What is unavailable Swaps remain disabled until compatible liquidity exists. Missing activity is not an error, and absent USD metrics must not be shown as zero-value trading. Add initial liquidity Choose Create Position , then select a range, distribution, and token amounts. The creation transaction and liquidity transaction are separate unless the review explicitly proves otherwise. If pool creation succeeds but the liquidity step is rejected or reverts, the pool still exists. Reopen it, refresh the active price and balances, and prepare a new liquidity review. Do not retry pool creation. A new contract address has no inherent liquidity, users, price accuracy, or asset quality."
  },
  "pools/swap": {
    "headings": [
      {
        "depth": 2,
        "id": "native-swaps",
        "title": "Native swaps"
      }
    ],
    "searchText": "An exact-input swap spends the amount you enter and protects a minimum amount received. 1. Open the exact pool and choose Swap . 2. Select the direction and enter the input amount. 3. Review expected output, minimum received, fees, price impact, execution price, and deadline. 4. Approve the input token when required. 5. Review the refreshed quote and exact wallet request. 6. Submit, then wait for the required confirmation state. Reversing direction or changing amount, pool, account, chain, slippage, or deadline invalidates the prior quote. Native swaps ETH input uses native balance and transaction value. It never requires an ERC-20 approval. WETH is a token contract and follows ERC-20 approval rules even when its underlying asset is ETH. An approval only grants spending permission. Feather refreshes balances, allowance, and quote before preparing the separate swap transaction."
  },
  "pools/swap-settings": {
    "headings": [
      {
        "depth": 2,
        "id": "slippage-tolerance",
        "title": "Slippage tolerance"
      },
      {
        "depth": 2,
        "id": "deadline",
        "title": "Deadline"
      },
      {
        "depth": 2,
        "id": "price-impact",
        "title": "Price impact"
      }
    ],
    "searchText": "Slippage tolerance Slippage tolerance determines the protected minimum received. A wider tolerance makes execution possible across more price movement but permits a worse result. Feather does not silently increase it. Deadline The deadline limits how long a prepared transaction remains eligible for execution. An expired transaction should fail instead of executing against much later market state. Price impact Price impact estimates how much the trade itself changes execution price by consuming liquidity. Thin pools and large trades generally create more impact. Review value Meaning --- --- Expected output Current quoted amount before protection Minimum received Lowest protected output under selected tolerance Execution price Effective price for the reviewed trade Price impact Estimated trade-driven movement from available liquidity State can change before confirmation. The transaction may revert, expire, or receive an amount above the minimum but below the earlier expectation."
  },
  "pools/workspace": {
    "headings": [
      {
        "depth": 2,
        "id": "persistent-identity",
        "title": "Persistent identity"
      },
      {
        "depth": 2,
        "id": "workspace-regions",
        "title": "Workspace regions"
      }
    ],
    "searchText": "The pool workspace keeps market context visible while you inspect or prepare an action. Persistent identity The header shows the token pair, full pool address, bin step, and fee information. The market area carries the current displayed price and surfaces an explicit state when source data is unavailable. Copy the full address when comparing it with an explorer or wallet request. Workspace regions - The market view shows selectable price-history intervals and liquidity distribution. - The position view shows holdings owned by the connected wallet in this pool. - History distinguishes swaps, liquidity additions, and removals. - The action rail switches between Create Position, Swap, and Manage without changing pools. On mobile, these regions become tabs, drawers, or sheets. The selected pool and transaction review remain available without horizontal page scrolling. Reloading or sharing a pool URL must not fall back to a different address when the requested pool is missing or unsupported."
  },
  "safety/erc20-approvals": {
    "headings": [
      {
        "depth": 2,
        "id": "review-fields",
        "title": "Review fields"
      }
    ],
    "searchText": "An ERC-20 approval authorizes a spender contract to transfer a token from your wallet up to the allowance limit. Review fields Confirm the token symbol and full address, approval amount or cap, current allowance, full spender address, account, and network. An approval remains active until used, changed, or revoked according to token behavior. Feather skips approval when the current allowance is sufficient. If the allowance is missing, stale, or revoked, a new approval and refreshed transaction review are required. Approving the wrong token, spender, network, or amount can expose funds. Compare the wallet request with Feather's disclosure before signing. Native ETH never uses an ERC-20 approval. WETH does."
  },
  "safety/eth-weth": {
    "headings": [],
    "searchText": "ETH is Robinhood Chain's native currency. It pays gas and can be supplied as transaction value. WETH is an ERC-20 contract representing wrapped ETH. Property ETH WETH --- --- --- Balance source Native account balance Token contract balance Approval Never Required when a spender needs it Transfer mechanism Transaction value or native transfer ERC-20 transfer Gas payment Yes No A pool can use the wrapped-native contract while the interface offers a native ETH mode. Review must state whether output arrives as ETH or WETH. Using maximum ETH must reserve enough native balance for network fees. A WETH balance cannot pay gas without first becoming native ETH through an explicit action."
  },
  "safety/gas": {
    "headings": [
      {
        "depth": 2,
        "id": "estimated-cost",
        "title": "Estimated cost"
      },
      {
        "depth": 2,
        "id": "insufficient-gas",
        "title": "Insufficient gas"
      }
    ],
    "searchText": "Every approval, pool creation, swap, add, and removal is an EVM transaction that consumes gas. Estimated cost Feather simulates the exact transaction, estimates its gas requirement, applies a documented buffer, and combines it with the current gas price. This is not an exact final-cost guarantee. The wallet can present updated fee information. Price or gas changes before acceptance can require a refreshed review. Insufficient gas An ETH shortage is distinct from an insufficient token balance. Token Max uses the token balance, while ETH Max preserves a native reserve for the transaction and any required approvals. Liquidity Book positions do not create refundable accounts. Network fees pay for computation and confirmation."
  },
  "safety/incomplete-information": {
    "headings": [],
    "searchText": "Feather treats missing, partial, stale, and zero as different states. - Loading: the requested information has not completed. - Unavailable: a value cannot currently be obtained. - Partial: some facts are present, but the complete set is not established. - Stale: information is older than the allowed execution boundary. - Zero: the trusted current value is actually zero. Read-only presentation can remain visible while dependent actions are disabled. For example, missing USD value does not imply zero value, and an incomplete owned-bin set cannot support a full exit. Refresh or retry the named condition. Switching pages, reconnecting repeatedly, or increasing transaction tolerance does not make untrusted state safe."
  },
  "safety/lb-operator-approvals": {
    "headings": [
      {
        "depth": 2,
        "id": "scope",
        "title": "Scope"
      }
    ],
    "searchText": "Liquidity Book balances use a pair-wide operator approval. This permission differs from a token allowance. Scope The approval authorizes the router to operate all bin balances issued by one LBPair contract for your wallet. It is not limited to the bins currently selected in the withdrawal form. Review the full pair contract address, full router address, connected owner, network, current approval state, and persistent all-bin scope. The withdrawal transaction burns only its specified bins, but the standing operator permission applies across that pair contract until revoked. If approval already exists, Feather skips the request. A stale or revoked state requires a fresh check before removal."
  },
  "safety/rejected-reverted": {
    "headings": [
      {
        "depth": 2,
        "id": "rejected",
        "title": "Rejected"
      },
      {
        "depth": 2,
        "id": "reverted",
        "title": "Reverted"
      },
      {
        "depth": 2,
        "id": "replaced-or-dropped",
        "title": "Replaced or dropped"
      },
      {
        "depth": 2,
        "id": "unknown-submission",
        "title": "Unknown submission"
      }
    ],
    "searchText": "Rejected The wallet did not submit the request. Review current state before trying again. Reverted The transaction was mined but execution failed. Gas was still consumed. Refresh balances, approvals, pool state, and the specific error before rebuilding. Replaced or dropped A replacement uses another hash for the same nonce. A dropped transaction may disappear without a receipt. Feather reconciles the account and known hashes before enabling retry. Unknown submission A provider error can occur after possible broadcast but before the application receives a hash. Do not blindly resubmit. Check wallet activity, account nonce, pending transactions, and explorer history first. Another tab or device must independently refresh balance, allowance, and live state. Do not assume application-wide idempotency."
  },
  "safety/token-hook-warnings": {
    "headings": [
      {
        "depth": 2,
        "id": "token-warnings",
        "title": "Token warnings"
      },
      {
        "depth": 2,
        "id": "hook-warnings",
        "title": "Hook warnings"
      },
      {
        "depth": 2,
        "id": "contract-mismatch",
        "title": "Contract mismatch"
      }
    ],
    "searchText": "Token warnings Known fee-on-transfer, rebasing, blacklistable, upgradeable, or suspicious assets can be restricted. Feather does not claim to detect every unusual behavior at runtime. Hook warnings Pool hooks can change behavior around liquidity and swaps. Writes are enabled only for hookless or explicitly supported configurations. Unknown hook identity or code blocks execution. Contract mismatch Before writes, Feather verifies that the pair belongs to the configured factory and matches expected tokens, order, bin step, hook settings, network, and deployed code. If an address, owner, factory, token, or code check fails, treat the pool as read-only and do not reproduce the transaction elsewhere."
  },
  "safety/transaction-lifecycle": {
    "headings": [
      {
        "depth": 2,
        "id": "review-to-submission",
        "title": "Review to submission"
      },
      {
        "depth": 2,
        "id": "submitted",
        "title": "Submitted"
      },
      {
        "depth": 2,
        "id": "receipt-and-confirmations",
        "title": "Receipt and confirmations"
      },
      {
        "depth": 2,
        "id": "replacement-or-reorganization",
        "title": "Replacement or reorganization"
      }
    ],
    "searchText": "Review to submission Before wallet handoff, editing a bound field cancels the unsubmitted review. After handoff, the original request remains independent from later edits. Submitted Once a transaction hash exists, Feather tracks it under the submitting account, chain, action, and contract context. Reloading the page should not replay it. Receipt and confirmations A successful receipt proves execution in one block. The application can require additional confirmations before treating it as canonical success. Other views may take longer to reflect the result. Replacement or reorganization A wallet can replace a pending transaction. A chain reorganization can temporarily remove a prior receipt. Feather keeps related hashes linked and reconciles whether the action is re-included, absent, reverted, or confirmed again. Only the required confirmed receipt state establishes completion. A wallet prompt or broadcast alone does not."
  },
  "safety/transaction-review": {
    "headings": [
      {
        "depth": 2,
        "id": "simulation",
        "title": "Simulation"
      }
    ],
    "searchText": "Before wallet handoff, Feather binds the account, chain, deployment, pool, token order, amounts, settings, recipient, refund destination, approval state, and current market context into one executable review. Simulation The exact target, calldata, and native value are simulated against current chain state. A simulation failure blocks submission and should identify the condition that needs attention. Changing account, chain, pool, direction, amount, strategy, range, slippage, deadline, approval, balance, active bin, or other bound context invalidates the review. Simulation reduces avoidable failure but cannot replace wallet review or guarantee confirmation. Reject any wallet request that differs from the application disclosure."
  },
  "safety/vulnerability": {
    "headings": [
      {
        "depth": 2,
        "id": "include",
        "title": "Include"
      },
      {
        "depth": 2,
        "id": "never-include",
        "title": "Never include"
      }
    ],
    "searchText": "Do not open a public issue for a suspected vulnerability. Use the verified private security intake linked by the official application when it becomes available. Include - affected component and observed version; - clear reproduction steps using accounts and environments you control; - expected and actual behavior; - potential impact; - suggested mitigation when known. Never include - seed phrases or private keys; - production credentials or authorization values; - unrelated wallet or browser information; - funds that you do not own; - public exploit instructions before coordinated disclosure. Do not probe accounts, contracts, hosts, or environments you are not authorized to use. Minimize impact and stop when the issue is demonstrated."
  },
  "safety/wallet-network": {
    "headings": [
      {
        "depth": 2,
        "id": "wallet-is-not-detected",
        "title": "Wallet is not detected"
      },
      {
        "depth": 2,
        "id": "wallet-is-locked-or-unauthorized",
        "title": "Wallet is locked or unauthorized"
      },
      {
        "depth": 2,
        "id": "wrong-chain",
        "title": "Wrong chain"
      },
      {
        "depth": 2,
        "id": "wrong-account-or-stale-balances",
        "title": "Wrong account or stale balances"
      }
    ],
    "searchText": "Wallet is not detected Confirm a supported wallet is installed and enabled. Reload after installation. If several injected wallets are present, select the intended provider explicitly. Wallet is locked or unauthorized Unlock it, open the account-access control, and authorize the site. A rejected permission is not a successful connection. Wrong chain Use the application's network switch request and inspect it in the wallet. If the visible wallet network is correct but Feather still blocks execution, refresh and verify that all configured chain checks agree. Wrong account or stale balances Confirm the displayed full address. Disconnect and reconnect only when needed, then wait for owner-specific balances, approvals, and positions to reload. Use chain details presented by the official application and verify them independently."
  },
  "welcome": {
    "headings": [
      {
        "depth": 2,
        "id": "start-with-a-goal",
        "title": "Start with a goal"
      },
      {
        "depth": 2,
        "id": "what-you-need",
        "title": "What you need"
      }
    ],
    "searchText": "Feather is a non-custodial exchange built around Liquidity Book pools. You trade from your own wallet, or provide liquidity across selected price bins to earn a share of eligible trading fees. Start with a goal - Trade: discover a pool, review its exact address and bin step, then swap inside that pool. - Provide liquidity: choose a range and distribution strategy, approve the required assets, and create a position. - Manage a position: inspect current token claims, add more liquidity, withdraw part of the position, or exit every live bin. - Build directly: review the public contract architecture and integration safety requirements. Feather cannot recover wallet keys, reverse confirmed transactions, guarantee returns, or prevent losses caused by market movement or contract risk. What you need Use a supported EVM wallet, select Robinhood Chain, keep enough ETH for gas, and verify every token and contract address before approving a transaction."
  }
} as Record<string, { headings: DocHeading[]; searchText: string }>;
